video_source:                                                                                                                                                                                                                                                                                                                                                                                                                                  
    video_path_vit_0: "source/jellyfish.mp4"                                                
    video_path_vit_1:  "source/baboon.mp4" 
    video_path_vit_2:  "source/bison.mp4"   
    video_path_vit_3:  "source/chain.mp4" 
    video_path_vit_4:  "source/parachute.mp4" 
    video_path_vit_5:  "source/snail.mp4" 
    video_path_vit_6:  "source/umbrella.mp4"     
    video_path_vit_7:  "source/white_stork.mp4" 
                                                      
logo:                                                                                
    logo_path: "source/logo.png"
    up_width: 1.5
    up_height: 1.5
                              
title:                                                                                      
    fontScale: 0.8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    thickness: 3                        
    org: [15, 40]                                                                                            
    text_color: [0, 0, 0]                              
    text_background_color: 255                                    
    text_area_yolo: [60, 500, 3]  
    text_area_vit: [60, 530, 3]                                                                                                                  
                                                                                                                                                                                                                                
task_vit:                                                       
    task_text: "ViT-B-16 WITH OBJECT CLASSIFICATION"
                  
display_ViT:                                                                                
    fontScale_vit: 0.8                                                                                                                                                                                                                                                                                           
    thickness_vit: 2   
    org_vit_category: [15, 120]                                                                                                                                     
    org_vit_probability: [15, 150]                                                                                                                                                                                                          
    color_vit: [0, 0, 255]                                                                                                        
                                                                            
display_resolution:                                                
    up_width: 1920                                                                                                 
    up_height: 1080   
                                                                                                                
window:                                                                                                                                                                                                                                                                               
    window_name: "ViT-B-16"   
                                                                                                                         
output_video:                                                                                                                                                                                                                                                                                                          
    video_name: 'source/output_video.mp4'
    fps: 33
                          
    
    
    
    
    
    
