video_source:                                                                                                                               
    video_path_yolo: 'source/traffic.mp4'                                                                                                                                                                                                                                                                                                        
                                         
yolov13_weight_cfg:                      
    yolov13_weights_path: "models/yolov13n.pt"                                                    
    yolov13_cfg_path: 'ultralytics/cfg/models/v13/yolov13.yaml' 
                       
logo:                                                                                                                                                                                                               
    logo_path: "source/logo.png"                                                                                                      
    up_width: 1.5
    up_height: 1.5
                              
title:                                                                                      
    fontScale: 0.8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    thickness: 3                        
    org: [15, 40]                                                                                            
    text_color: [0, 0, 0]                              
    text_background_color: 255                                    
    text_area_yolo: [60, 500, 3]  
    text_area_vit: [60, 530, 3]                                                                                                                  
                                                                                                                                       
task_yolo:       
    task_text: "YOLOv13-N WITH OBJECT DETECTION" 
                                                                                                                                                                                                  
yolov13_features:                                                                                                                   
    imgsz: 640                                                                                                       
    conf_thres: 0.25                                                                                                                          
    iou_thres: 0.45                                                                      
    fontScale_yolo_ori: 5    
    
distinct_colors:                                                                                                                              
    colors_0: [255, 0, 0]  
    colors_1: [0, 255, 0] 
    colors_2: [0, 0, 255] 
    colors_3: [255, 255, 0]
    colors_4: [255, 0, 255] 
    colors_5: [0, 255, 255]
    colors_6: [255, 255, 255] 
    colors_7: [125, 125, 125]
                                                                            
display_resolution:                                                
    up_width: 1920                                                                                                 
    up_height: 1080   
                                                                                   
coco:             
    coco_path: coco.names
                                                            
window:                                                                                                                                                                                                                                                                                                                                                                                                                               
    window_name: "YOLOv13-N"   
                                                                                                                    
output_video:                                                                                                                                                                                                                                                                                                          
    video_name: 'source/output_video.mp4'
    fps: 33
    
    
    
    
    
